---
- hosts: all
  remote_user: root
  tasks:
    - include: install_apache.yml

    - name: check apache service
      service: name={{ package_name }} state=started
#      debug: msg={{ ansible_distribution }}
#      sudo: yes

- hosts: all
  remote_user: root
  tasks:

    - name: install httpd package
      yum: name=httpd state=absent
#      sudo: yes

#    - name: starting httpd service
#      service: name=httpd state=started
#      sudo: yes
...
